# Generated by Django 5.2 on 2025-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('date_published', models.DateTimeField()),
                ('is_fake', models.BooleanField()),
            ],
        ),
    ]
